### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Deyclan** [PolytechLyon/pattern-strategy-tp3-piard-serrano#1]

**Comment by k33g** [comment]
Bonjour @Deyclan 
Il est généralement de bon ton lorsque l'on assigne une issue à quelqu'un de lui mettre un petit message (comme bonjour par exemple) 
Mais en général une issue doit toujours avoir un message

Les explications de vos exercices sont bien détaillées

ok sur votre avis sur le pattern

Pour les cas d'utilisation, le 1er ok, le 2ème soit, le 3ème un peu trop générique

**Comment by Deyclan** [comment]
Bonjour @k33g, 
Désolé pour ce manque de manière, il s'agit d'une erreure de manipulation de ma part ( Je pensais avoir ajouté un commentaire via mon téléphone mais il n'a apparement pas été pris en compte ...  😞)

Pour le 3ème cas d'utilisation, je dois avouer avoir manqué d'un peu d'inspiration. Après réflexions, un autre cas d'utilisation plus précis serait celui d'un algorithme de formattage ou chaque format serait une strategie

**Comment by k33g** [comment]
@Deyclan hello, à mettre dans le rapport avec un petit exemple 😄

**Comment by Deyclan** [comment]
Bonsoir @k33g, nous avons rajouté le 3 ème cas d'utilisation du DP Strategy ! Y'a-t'il d'autres choses à ajouter ou pouvons nous close l'issue ? 😃
